version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: monday
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "@types/jquery"
      update-types: ["version-update:semver-major"]
    - dependency-name: "@types/react"
      update-types: ["version-update:semver-major"]
    - dependency-name: "@types/react-dom"
      update-types: ["version-update:semver-major"]
    - dependency-name: "jquery"
      update-types: ["version-update:semver-major"]
    - dependency-name: "react"
      update-types: ["version-update:semver-major"]
    - dependency-name: "react-dom"
      update-types: ["version-update:semver-major"]
    - dependency-name: "jsdom"
      update-types: ["version-update:semver-major"]
  groups:
    all-npm-updates:
      patterns:
        - "*"
